### ISSUE TITLE
problem with orFilter

### ISSUE THREAD

**Issue by rayden7** [danpaz/bodybuilder#122] opened 2017-03-06 03:46 UTC
I'm not able to get an orFilter to work the same way that the demo website has them shown - even when I use the repl.js, I'm getting an empty section where the "should" part of the filter is expected.  Example:

$ node ./node_modules/bodybuilder/repl.js
bodybuilder > bodybuilder().orFilter('term', 'email', 'kimchee@kimchee.com').orFilter('term', 'username', 'kimchee').build()
`{ query: { bool: { filter: [Object] } } }`

When I have the same query in my IDE and hit that line in the debugger, I can see that the query looks like this:
`{"query":{"bool":{"filter":{"bool":{}}}}}`

What I was expecting to see would have been:
`
{
  "query": {
    "bool": {
      "filter": {
        "bool": {
          "should": [
            {
              "term": {
                "email": "kimchee@kimchee.com"
              }
            },
            {
              "term": {
                "username": "kimchee"
              }
            }
          ]
        }
      }
    }
  }
}
`

Any ideas on what I'm doing wrong here?  I'm using node 6.9.1 and npm 3.10.8 on OSX 10.12.3.

**Comment by bdgamble** [comment] 2017-03-14 19:57
I am also seeing this behaviour.

**Comment by rayden7** [comment] 2017-03-14 20:23
Definitely some inconsistent behavior on this one - 

`$ node ./node_modules/bodybuilder/repl.js 
bodybuilder > bodybuilder().orFilter('term', 'email', 'kimchee@kimchee.com').orFilter('term', 'username', 'kimchee').build()

{ query: { bool: { filter: [Object] } } }

bodybuilder > bodybuilder().orFilter('term', 'email', 'kimchee@kimchee.com').orFilter('term', 'username', 'kimchee').getFilter()

{ bool: { should: [ [Object], [Object] ] } }`

**Comment by bdgamble** [comment] 2017-03-15 17:16
I forked the repo and was able to produce a fix that locally fixed my issue, but I have been unable to produce a test that fails before the fix and works after. All my attempts work before and after, even equivalent filters to the one I have that is failing locally. I wonder if this is a babel transpilation issue?

**Comment by bdgamble** [comment] 2017-03-24 20:37
I believe I have found the cause of this behaviour, and I hope it solves it for you too @rayden7. In my project I was using the module https://www.npmjs.com/package/should which was hijacking the should in the ES query, and being removed on build. Removing the should module fixed the problem for me, but I wonder if something can be done to protect against this as should is a fairly popular module.

**Comment by johannes-scharlach** [comment] 2017-08-13 11:47
@bdgamble great find!

Some internal workings of bodybuilder have changed lately, so there is a good chance that the issue is solved now. Could you confirm for me if it's fixed in version 2.2?

I'll close this issue for now, since it's not an issue with bodybuilder itself but with how it interacts with other packages.

**Closed by johannes-scharlach** 2017-08-13 11:47 UTC

**Comment by yzuoran** [comment] 2017-09-26 06:29
@johannes-scharlach I'm using the version 2.2.6, sadly cannot work with the should package yet...so 
simply want to know...the problem will be resolved in the next version?

**Comment by yzuoran** [comment] 2017-09-26 06:44
the problem would solved by update the should package...

**Comment by jonberke** [comment] 2017-10-09 23:00
Unfortunately it's not fixed in version 2.2.  I just ran into using the latest version of bodybuilder (2.2.6) and the should module.

**Comment by ferronrsmith** [comment] 2017-10-10 03:16
This is really an issue with `should.js` patching the `Object.prototype` with its own implementation. Not a `bodybuilder` issue. You can use the noConflict mode in `should.js`

http://shouldjs.github.io/#should-noconflict
