### ISSUE TITLE
Nested bool query with must

### ISSUE THREAD

**Issue by petoknm** [danpaz/bodybuilder#162] opened 2018-01-24 23:18 UTC
I have a really difficult time trying to build this type of query
```
{
    "query": {
        "bool": {
            "must": {
                "bool" : { "should": [
                      { "match": { "title": "Elasticsearch" }},
                      { "match": { "title": "Solr" }} ] }
            },
            "must": { "match": { "authors": "clinton gormely" }},
            "must_not": { "match": {"authors": "radu gheorge" }}
        }
    }
}
```
Because when constructing the nested `bool` with a `should` inside, the library puts an extra `query` key there. So the output of this
```
bodybuilder()
        .query('match', 'message', 'this is a test')
	.query('bool', b => b.orQuery('match', 'm', 'asd').orQuery('match', 'm', 'dsa'))
        .build()
```
is 
```
{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "message": "this is a test"
          }
        },
        {
          "bool": {
            "query": {
              "bool": {
                "should": [
                  {
                    "match": {
                      "m": "asd"
                    }
                  },
                  {
                    "match": {
                      "m": "dsa"
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  }
}
```
Which is not a valid query. But changing the query to a filter works fine:
```
bodybuilder()
	.query('match', 'message', 'this is a test')
	.filter('bool', b => b.orFilter('match', 'm', 'asd').orFilter('match', 'm', 'dsa'))
        .build()
```
with the following output
```
{
  "query": {
    "bool": {
      "filter": {
        "bool": {
          "should": [
            {
              "match": {
                "m": "asd"
              }
            },
            {
              "match": {
                "m": "dsa"
              }
            }
          ]
        }
      },
      "must": {
        "match": {
          "message": "this is a test"
        }
      }
    }
  }
}
```
Is this a bug or am I just missing something?
Thanks

**Comment by ferronrsmith** [comment] 2018-01-25 00:03
```json
bodybuilder()
        .query('bool', b => b.orQuery('match', 'title', 'Solr').orQuery('match', 'title', 'Elasticsearch'))
	.query('match', 'authors', 'clinton gormely')
        .notQuery('match', 'authors', 'radu gheorge').build()
```

=>

```json
{
  "query": {
    "bool": {
      "must": [
        {
          "bool": {
            "query": {
              "bool": {
                "should": [
                  {
                    "match": {
                      "title": "Solr"
                    }
                  },
                  {
                    "match": {
                      "title": "Elasticsearch"
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "match": {
            "authors": "clinton gormely"
          }
        }
      ],
      "must_not": [
        {
          "match": {
            "authors": "radu gheorge"
          }
        }
      ]
    }
  }
}
```
Definitely seems like a bug

**Comment by danpaz** [comment] 2018-01-25 16:02
Agree it's a bug and likely a duplicate of https://github.com/danpaz/bodybuilder/issues/142

**Closed** 2018-01-30 06:08 UTC
Labels: bug
